# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'BuyerUI.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QSpacerItem, QStackedWidget, QVBoxLayout, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QSize(1280, 720))
        MainWindow.setMaximumSize(QSize(1280, 720))
        MainWindow.setStyleSheet(u"QWidget::setFixedSize(1366,768)")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.sidebar_widget = QWidget(self.centralwidget)
        self.sidebar_widget.setObjectName(u"sidebar_widget")
        self.sidebar_widget.setGeometry(QRect(0, 0, 281, 741))
        self.sidebar_widget.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.logo_frame = QFrame(self.sidebar_widget)
        self.logo_frame.setObjectName(u"logo_frame")
        self.logo_frame.setGeometry(QRect(10, 10, 261, 131))
        self.logo_frame.setFrameShape(QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.logo_frame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.ngyopify_logo = QLabel(self.logo_frame)
        self.ngyopify_logo.setObjectName(u"ngyopify_logo")
        self.ngyopify_logo.setPixmap(QPixmap(u":/Ecom App/png/NGYOPIFY.png"))
        self.ngyopify_logo.setScaledContents(True)

        self.horizontalLayout.addWidget(self.ngyopify_logo)

        self.horizontalSpacer = QSpacerItem(105, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.horizontalSpacer_2 = QSpacerItem(104, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)

        self.categories_dropdownButton = QPushButton(self.sidebar_widget)
        self.categories_dropdownButton.setObjectName(u"categories_dropdownButton")
        self.categories_dropdownButton.setGeometry(QRect(40, 180, 201, 41))
        self.categories_dropdownButton.setMaximumSize(QSize(201, 41))
        icon = QIcon()
        icon.addFile(u":/Ecom App/png/categories_logo_notSelected.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon.addFile(u":/Ecom App/png/categories_logo_Selected.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        icon.addFile(u":/Ecom App/png/categories_logo_notSelected.png", QSize(), QIcon.Mode.Selected, QIcon.State.Off)
        icon.addFile(u":/Ecom App/png/categories_logo_Selected.png", QSize(), QIcon.Mode.Selected, QIcon.State.On)
        self.categories_dropdownButton.setIcon(icon)
        self.categories_dropdownButton.setIconSize(QSize(350, 100))
        self.categories_dropdownButton.setCheckable(True)
        self.categories_dropdownButton.setChecked(False)
        self.categories_dropdownButton.setAutoExclusive(False)
        self.categories_dropdownButton.setAutoRepeatDelay(299)
        self.settings_pushButton = QPushButton(self.sidebar_widget)
        self.settings_pushButton.setObjectName(u"settings_pushButton")
        self.settings_pushButton.setGeometry(QRect(40, 640, 81, 31))
        self.settings_pushButton.setStyleSheet(u"QPushButton {\n"
"	border:none;\n"
"}")
        icon1 = QIcon()
        icon1.addFile(u":/Ecom App/png/settings_logo_notSelected.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon1.addFile(u":/Ecom App/png/settings_logo_Selected.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        icon1.addFile(u":/Ecom App/png/settings_logo_notSelected.png", QSize(), QIcon.Mode.Selected, QIcon.State.Off)
        icon1.addFile(u":/Ecom App/png/settings_logo_Selected.png", QSize(), QIcon.Mode.Selected, QIcon.State.On)
        self.settings_pushButton.setIcon(icon1)
        self.settings_pushButton.setIconSize(QSize(80, 80))
        self.settings_pushButton.setCheckable(True)
        self.settings_pushButton.setChecked(False)
        self.settings_pushButton.setAutoExclusive(True)
        self.categories_frame = QFrame(self.sidebar_widget)
        self.categories_frame.setObjectName(u"categories_frame")
        self.categories_frame.setGeometry(QRect(50, 230, 181, 321))
        self.categories_frame.setStyleSheet(u"QPushButton {\n"
"	border:none;\n"
"}")
        self.categories_frame.setFrameShape(QFrame.StyledPanel)
        self.categories_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.categories_frame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.booksStationary_pushButton = QPushButton(self.categories_frame)
        self.booksStationary_pushButton.setObjectName(u"booksStationary_pushButton")
        self.booksStationary_pushButton.setMinimumSize(QSize(161, 41))
        self.booksStationary_pushButton.setMaximumSize(QSize(161, 41))
        icon2 = QIcon()
        icon2.addFile(u":/Ecom App/png/BooksStationery_icon_notSelected.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.booksStationary_pushButton.setIcon(icon2)
        self.booksStationary_pushButton.setIconSize(QSize(160, 160))
        self.booksStationary_pushButton.setCheckable(True)
        self.booksStationary_pushButton.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.booksStationary_pushButton)

        self.clothingFashion_pushButton = QPushButton(self.categories_frame)
        self.clothingFashion_pushButton.setObjectName(u"clothingFashion_pushButton")
        self.clothingFashion_pushButton.setMinimumSize(QSize(161, 41))
        self.clothingFashion_pushButton.setMaximumSize(QSize(161, 41))
        icon3 = QIcon()
        icon3.addFile(u":/Ecom App/png/ClothingFashion_icon_notSelected.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.clothingFashion_pushButton.setIcon(icon3)
        self.clothingFashion_pushButton.setIconSize(QSize(160, 160))
        self.clothingFashion_pushButton.setCheckable(True)
        self.clothingFashion_pushButton.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.clothingFashion_pushButton)

        self.electronicsGadgets_pushButton = QPushButton(self.categories_frame)
        self.electronicsGadgets_pushButton.setObjectName(u"electronicsGadgets_pushButton")
        self.electronicsGadgets_pushButton.setMinimumSize(QSize(161, 41))
        self.electronicsGadgets_pushButton.setMaximumSize(QSize(161, 41))
        icon4 = QIcon()
        icon4.addFile(u":/Ecom App/png/ElectronicsGadgets_icon_notSelected.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.electronicsGadgets_pushButton.setIcon(icon4)
        self.electronicsGadgets_pushButton.setIconSize(QSize(160, 160))
        self.electronicsGadgets_pushButton.setCheckable(True)
        self.electronicsGadgets_pushButton.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.electronicsGadgets_pushButton)

        self.foodSnacks_pushButton = QPushButton(self.categories_frame)
        self.foodSnacks_pushButton.setObjectName(u"foodSnacks_pushButton")
        self.foodSnacks_pushButton.setMinimumSize(QSize(161, 41))
        self.foodSnacks_pushButton.setMaximumSize(QSize(161, 41))
        icon5 = QIcon()
        icon5.addFile(u":/Ecom App/png/FoodSnacks_icon_notSelected.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.foodSnacks_pushButton.setIcon(icon5)
        self.foodSnacks_pushButton.setIconSize(QSize(160, 160))
        self.foodSnacks_pushButton.setCheckable(True)
        self.foodSnacks_pushButton.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.foodSnacks_pushButton)

        self.healthBeauty_pushButton = QPushButton(self.categories_frame)
        self.healthBeauty_pushButton.setObjectName(u"healthBeauty_pushButton")
        self.healthBeauty_pushButton.setMinimumSize(QSize(161, 41))
        self.healthBeauty_pushButton.setMaximumSize(QSize(161, 41))
        icon6 = QIcon()
        icon6.addFile(u":/Ecom App/png/HealthBeauty_icon_notSelected.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.healthBeauty_pushButton.setIcon(icon6)
        self.healthBeauty_pushButton.setIconSize(QSize(160, 160))
        self.healthBeauty_pushButton.setCheckable(True)
        self.healthBeauty_pushButton.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.healthBeauty_pushButton)

        self.homeLiving_pushButton = QPushButton(self.categories_frame)
        self.homeLiving_pushButton.setObjectName(u"homeLiving_pushButton")
        self.homeLiving_pushButton.setMinimumSize(QSize(161, 41))
        self.homeLiving_pushButton.setMaximumSize(QSize(161, 41))
        icon7 = QIcon()
        icon7.addFile(u":/Ecom App/png/HomeLiving_icon_notSelected.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.homeLiving_pushButton.setIcon(icon7)
        self.homeLiving_pushButton.setIconSize(QSize(160, 160))
        self.homeLiving_pushButton.setCheckable(True)
        self.homeLiving_pushButton.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.homeLiving_pushButton)

        self.homeLiving_pushButton_2 = QPushButton(self.categories_frame)
        self.homeLiving_pushButton_2.setObjectName(u"homeLiving_pushButton_2")
        self.homeLiving_pushButton_2.setMinimumSize(QSize(161, 41))
        self.homeLiving_pushButton_2.setMaximumSize(QSize(161, 41))
        icon8 = QIcon()
        icon8.addFile(u":/Ecom App/png/other_icon_notSelected.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.homeLiving_pushButton_2.setIcon(icon8)
        self.homeLiving_pushButton_2.setIconSize(QSize(160, 160))
        self.homeLiving_pushButton_2.setCheckable(True)
        self.homeLiving_pushButton_2.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.homeLiving_pushButton_2)

        self.horizontal_line = QFrame(self.sidebar_widget)
        self.horizontal_line.setObjectName(u"horizontal_line")
        self.horizontal_line.setGeometry(QRect(40, 600, 191, 20))
        self.horizontal_line.setFrameShape(QFrame.Shape.HLine)
        self.horizontal_line.setFrameShadow(QFrame.Shadow.Sunken)
        self.navigationBar_widget = QWidget(self.centralwidget)
        self.navigationBar_widget.setObjectName(u"navigationBar_widget")
        self.navigationBar_widget.setGeometry(QRect(280, 0, 1001, 141))
        self.navigationBar_widget.setStyleSheet(u"QWidget{\n"
"	background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton {\n"
"	border:none;\n"
"}\n"
"\n"
"QLineEdit {\n"
"	border:none;\n"
"}\n"
"\n"
"")
        self.searchbar_frame = QFrame(self.navigationBar_widget)
        self.searchbar_frame.setObjectName(u"searchbar_frame")
        self.searchbar_frame.setGeometry(QRect(0, 40, 811, 71))
        self.searchbar_frame.setFrameShape(QFrame.StyledPanel)
        self.searchbar_frame.setFrameShadow(QFrame.Raised)
        self.search_pushButton = QPushButton(self.searchbar_frame)
        self.search_pushButton.setObjectName(u"search_pushButton")
        self.search_pushButton.setGeometry(QRect(720, 10, 75, 51))
        font = QFont()
        font.setPointSize(9)
        self.search_pushButton.setFont(font)
        self.search_pushButton.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        icon9 = QIcon()
        icon9.addFile(u":/Ecom App/png/002-search-interface-symbol.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.search_pushButton.setIcon(icon9)
        self.search_pushButton.setIconSize(QSize(19, 18))
        self.searchBar_lineEdit = QLineEdit(self.searchbar_frame)
        self.searchBar_lineEdit.setObjectName(u"searchBar_lineEdit")
        self.searchBar_lineEdit.setGeometry(QRect(0, 10, 721, 51))
        font1 = QFont()
        font1.setPointSize(10)
        self.searchBar_lineEdit.setFont(font1)
        self.searchBar_lineEdit.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.addCart_pushButton = QPushButton(self.navigationBar_widget)
        self.addCart_pushButton.setObjectName(u"addCart_pushButton")
        self.addCart_pushButton.setGeometry(QRect(830, 60, 41, 31))
        icon10 = QIcon()
        icon10.addFile(u":/Ecom App/png/005-online-shopping.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.addCart_pushButton.setIcon(icon10)
        self.addCart_pushButton.setIconSize(QSize(30, 30))
        self.account_pushButton = QPushButton(self.navigationBar_widget)
        self.account_pushButton.setObjectName(u"account_pushButton")
        self.account_pushButton.setGeometry(QRect(910, 60, 41, 31))
        icon11 = QIcon()
        icon11.addFile(u":/Ecom App/png/009-user-1.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.account_pushButton.setIcon(icon11)
        self.account_pushButton.setIconSize(QSize(31, 31))
        self.menuCategories_frame = QFrame(self.centralwidget)
        self.menuCategories_frame.setObjectName(u"menuCategories_frame")
        self.menuCategories_frame.setGeometry(QRect(280, 140, 1001, 581))
        self.menuCategories_frame.setFrameShape(QFrame.StyledPanel)
        self.menuCategories_frame.setFrameShadow(QFrame.Raised)
        self.menuCategory_stackedWidget = QStackedWidget(self.menuCategories_frame)
        self.menuCategory_stackedWidget.setObjectName(u"menuCategory_stackedWidget")
        self.menuCategory_stackedWidget.setGeometry(QRect(0, 0, 1001, 581))
        self.menuCategory_stackedWidget.setMaximumSize(QSize(1001, 16777215))
        self.menuCategory_stackedWidget.setStyleSheet(u"background-color: rgb(0, 170, 127);")
        self.homepage_page_1 = QWidget()
        self.homepage_page_1.setObjectName(u"homepage_page_1")
        self.label_2 = QLabel(self.homepage_page_1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(210, 130, 751, 291))
        font2 = QFont()
        font2.setPointSize(41)
        self.label_2.setFont(font2)
        self.menuCategory_stackedWidget.addWidget(self.homepage_page_1)
        self.BS_page_2 = QWidget()
        self.BS_page_2.setObjectName(u"BS_page_2")
        self.label_3 = QLabel(self.BS_page_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(270, 110, 751, 291))
        self.label_3.setFont(font2)
        self.menuCategory_stackedWidget.addWidget(self.BS_page_2)
        self.CF_page_3 = QWidget()
        self.CF_page_3.setObjectName(u"CF_page_3")
        self.label_4 = QLabel(self.CF_page_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(140, 110, 751, 291))
        self.label_4.setFont(font2)
        self.menuCategory_stackedWidget.addWidget(self.CF_page_3)
        self.EGpage_4 = QWidget()
        self.EGpage_4.setObjectName(u"EGpage_4")
        self.label_5 = QLabel(self.EGpage_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(100, 160, 751, 291))
        self.label_5.setFont(font2)
        self.menuCategory_stackedWidget.addWidget(self.EGpage_4)
        self.FS_page_5 = QWidget()
        self.FS_page_5.setObjectName(u"FS_page_5")
        self.label_6 = QLabel(self.FS_page_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(180, 90, 751, 291))
        self.label_6.setFont(font2)
        self.menuCategory_stackedWidget.addWidget(self.FS_page_5)
        self.HB_page_6 = QWidget()
        self.HB_page_6.setObjectName(u"HB_page_6")
        self.label_7 = QLabel(self.HB_page_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(200, 100, 751, 291))
        self.label_7.setFont(font2)
        self.menuCategory_stackedWidget.addWidget(self.HB_page_6)
        self.HL_page_7 = QWidget()
        self.HL_page_7.setObjectName(u"HL_page_7")
        self.label_8 = QLabel(self.HL_page_7)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(270, 150, 751, 291))
        self.label_8.setFont(font2)
        self.menuCategory_stackedWidget.addWidget(self.HL_page_7)
        self.Other_page_8 = QWidget()
        self.Other_page_8.setObjectName(u"Other_page_8")
        self.label_9 = QLabel(self.Other_page_8)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(210, 130, 751, 291))
        self.label_9.setFont(font2)
        self.menuCategory_stackedWidget.addWidget(self.Other_page_8)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.categories_dropdownButton.toggled.connect(self.categories_frame.setHidden)

        self.menuCategory_stackedWidget.setCurrentIndex(7)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.ngyopify_logo.setText("")
        self.categories_dropdownButton.setText("")
        self.settings_pushButton.setText("")
        self.booksStationary_pushButton.setText("")
        self.clothingFashion_pushButton.setText("")
        self.electronicsGadgets_pushButton.setText("")
        self.foodSnacks_pushButton.setText("")
        self.healthBeauty_pushButton.setText("")
        self.homeLiving_pushButton.setText("")
        self.homeLiving_pushButton_2.setText("")
        self.search_pushButton.setText("")
        self.searchBar_lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"             Search", None))
        self.addCart_pushButton.setText("")
        self.account_pushButton.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"HOMEPAGE WELCOME", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"books", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"clothes", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"electronics", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"food", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"health", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"home", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"other", None))
    # retranslateUi

