# Form implementation generated from reading ui file 'checkout.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CheckoutWindow(object):
    def setupUi(self, CheckoutWindow):
        CheckoutWindow.setObjectName("CheckoutWindow")
        CheckoutWindow.resize(1280, 720)
        CheckoutWindow.setMinimumSize(QtCore.QSize(1280, 720))
        CheckoutWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(parent=CheckoutWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 311, 721))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 300, 271, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/bonethugz/Downloads/ngyopify_logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 140, 211, 31))
        self.label_3.setStyleSheet("font: 24pt \"Segoe UI\";\n"
"color: rgb(220, 29, 36);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 450, 81, 21))
        self.label_4.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.removeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.removeButton.setGeometry(QtCore.QRect(670, 450, 91, 23))
        self.removeButton.setStyleSheet("background-color: rgb(220, 29, 36);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Segoe UI\";")
        self.removeButton.setObjectName("removeButton")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(870, 140, 261, 41))
        self.label_5.setStyleSheet("font: 24pt \"Segoe UI\";\n"
"color: rgb(220, 29, 36);")
        self.label_5.setObjectName("label_5")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(870, 190, 261, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.name = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name)
        self.label_7 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.number = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.number.setObjectName("number")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.number)
        self.label_8 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.address = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.address.setObjectName("address")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.address)
        self.cartList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.cartList.setGeometry(QtCore.QRect(340, 180, 421, 261))
        self.cartList.setObjectName("cartList")
        self.CheckoutButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CheckoutButton.setGeometry(QtCore.QRect(874, 282, 251, 71))
        self.CheckoutButton.setStyleSheet("font: 28pt \"Segoe UI\";\n"
"background-color: rgb(220, 29, 36);\n"
"color: rgb(255, 255, 255);")
        self.CheckoutButton.setObjectName("CheckoutButton")
        self.backButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(340, 30, 75, 23))
        self.backButton.setStyleSheet("background-color: rgb(220, 29, 36);\n"
"font: 12pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.backButton.setObjectName("backButton")
        CheckoutWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CheckoutWindow)
        QtCore.QMetaObject.connectSlotsByName(CheckoutWindow)

    def retranslateUi(self, CheckoutWindow):
        _translate = QtCore.QCoreApplication.translate
        CheckoutWindow.setWindowTitle(_translate("CheckoutWindow", "Checkout"))
        self.label_3.setText(_translate("CheckoutWindow", "Checkout"))
        self.label_4.setText(_translate("CheckoutWindow", "Total: "))
        self.removeButton.setText(_translate("CheckoutWindow", "Remove Selected"))
        self.label_5.setText(_translate("CheckoutWindow", "Buyer Information"))
        self.label_6.setText(_translate("CheckoutWindow", "Full Name:"))
        self.label_7.setText(_translate("CheckoutWindow", "Contact Number:"))
        self.label_8.setText(_translate("CheckoutWindow", "Shipping Address:"))
        self.CheckoutButton.setText(_translate("CheckoutWindow", "CHECKOUT"))
        self.backButton.setText(_translate("CheckoutWindow", "Back"))
